import type { PortfolioConfig } from "../types/portfolioConfig";

const img = (name: string) => `/portfolio/${name}`;

export const portfolioConfig: PortfolioConfig = {
	brand: "Jason",
	brandAccent: "Chen",
	navLinks: [
		{ label: "KNOWLEDGE", href: "/knowledge/" },
		{ label: "PROJECTS", href: "/projects/" },
		{ label: "UNIVERSITY", href: "/works/" },
		{ label: "DIY", href: "/life/" },
		{ label: "MUSIC", href: "/music/" },
		{ label: "CONTACT", href: "/guestbook/" },
	],
	socialLinks: [
		{
			label: "CSDN",
			href: "https://blog.csdn.net/weixin_63844594",
			icon: "simple-icons:csdn",
		},
		{
			label: "GitHub",
			href: "https://github.com/Fz-a",
			icon: "simple-icons:github",
		},
		{
			label: "Gitee",
			href: "https://gitee.com/Fz_z",
			icon: "simple-icons:gitee",
		},
	],
	tagline: "",
	headline: "知行合一",
	bio: "",
	portrait: img("avatar.webp"),
	contactHref: "/guestbook/",
	contactEyebrow: "",
	contactTitle: "留墨",
	mottos: [],
	sections: [
		{
			id: "knowledge",
			title: "Knowledge",
			titleZh: "Knowledge",
			href: "/knowledge/",
			accent: "#525046",
			cover: img("nav-knowledge.webp"),
		},
		{
			id: "projects",
			title: "Projects",
			titleZh: "Projects",
			href: "/projects/",
			accent: "#3d3a34",
			cover: img("nav-projects.webp"),
		},
		{
			id: "works",
			title: "University",
			titleZh: "University",
			href: "/works/",
			accent: "#4a463e",
			cover: img("nav-works.webp"),
		},
		{
			id: "life",
			title: "DIY",
			titleZh: "DIY",
			href: "/life/",
			accent: "#2f2d28",
			cover: img("nav-life.webp"),
		},
		{
			id: "music",
			title: "Music",
			titleZh: "Music",
			href: "/music/",
			accent: "#3a3832",
			cover: img("nav-music.webp"),
		},
	],
	items: {
		knowledge: [
			{
				id: "hardware",
				title: "Hardware",
				summary: "Circuits, embedded systems, and physical interaction.",
				body: "Nest deeper folders here — MCU, sensing, RF, and more.",
				accent: "#3d3a34",
				kind: "folder",
				children: [
					{
						id: "mcu",
						title: "MCU & Embedded",
						summary: "Microcontrollers and embedded notes.",
						accent: "#525046",
						kind: "module",
					},
					{
						id: "sensing",
						title: "Sensing",
						summary: "Sensors and acquisition pipelines.",
						accent: "#4a463e",
						kind: "module",
					},
				],
			},
			{
				id: "software",
				title: "Software",
				summary: "Algorithms, front-end, and tooling.",
				body: "Split further into AI, Web, scripts, and more.",
				accent: "#4a463e",
				kind: "folder",
				children: [
					{
						id: "ai",
						title: "AI",
						summary: "Models and interactive experiments.",
						accent: "#3d3a34",
						kind: "module",
					},
				],
			},
			{
				id: "notes",
				title: "Notes & Essays",
				summary: "Writing and technical notes.",
				body: "Ideas gathered from reading and practice.",
				accent: "#525046",
				kind: "module",
				cover: img("knowledge-notes.webp"),
			},
			{
				id: "archive",
				title: "Archive",
				summary: "Browse by time.",
				accent: "#4a463e",
				kind: "module",
				cover: img("knowledge-archive.webp"),
			},
			{
				id: "topics",
				title: "Topics",
				summary: "Browse by theme.",
				accent: "#3d3a34",
				kind: "module",
				cover: img("knowledge-tags.webp"),
			},
		],
		projects: [
			{
				id: "smart-apparel",
				title: "Age-Friendly Apparel",
				summary:
					"Led an 11-person cross-major team. 20+ awards including national silver.",
				accent: "#3d3a34",
				cover: img("smart-apparel.webp"),
			},
			{
				id: "fire-warning",
				title: "Early Fire Warning",
				summary: "Academic project — sensing and early alert pipeline.",
				accent: "#4a463e",
				cover: img("fire-warning.webp"),
			},
			{
				id: "agv-remote",
				title: "AGV 2.4G Remote",
				summary: "Hardware remote design from concept to prototype.",
				accent: "#525046",
				cover: img("agv-remote.webp"),
			},
			{
				id: "rtk-module",
				title: "RTK Positioning",
				summary: "Circuit and structure work on RTK / AGV / AI terminals.",
				accent: "#2f2d28",
				cover: img("rtk-module.webp"),
			},
		],
		works: [
			{
				id: "interactive-visuals",
				title: "Realtime Visuals",
				summary: "TouchDesigner · ImmersiveDisplay · Stable Diffusion.",
				accent: "#4a463e",
				cover: img("interactive-visuals.webp"),
			},
			{
				id: "mapping",
				title: "Mapping Studies",
				summary: "Projection mapping principles and sensor hardware.",
				accent: "#3d3a34",
				cover: img("mapping.webp"),
			},
			{
				id: "pcb-layout",
				title: "Display PCB Layout",
				summary: "High-speed layout, impedance, and SMT practice at CVTE.",
				accent: "#525046",
				cover: img("pcb-layout.webp"),
			},
		],
		life: [
			{
				id: "maker-faire",
				title: "Maker Faire",
				summary: "Community and maker culture.",
				accent: "#2f2d28",
				cover: img("maker-faire.webp"),
			},
			{
				id: "expo",
				title: "Expos · SZ / GZ",
				summary: "Industry floors and demos.",
				accent: "#3d3a34",
				cover: img("expo.webp"),
			},
			{
				id: "chaihuo",
				title: "Chaihuo Makerspace",
				summary: "Shenzhen maker space sessions.",
				accent: "#4a463e",
				cover: img("chaihuo.webp"),
			},
			{
				id: "volunteer",
				title: "Campus Service",
				summary: "20+ volunteer sessions and promo leads.",
				accent: "#525046",
				cover: img("volunteer.webp"),
			},
		],
		music: [],
	},
};
